### ISSUE TITLE
Long compile operations cause maniacal resource consumption

### ISSUE THREAD

**Issue by kofno** [kofno/crystal-ide#1]
If a file triggers a particularly long compile operation, the ide server will spawn enough compiler instances to bog down all the computer's resources.

We'll probably have to dial back compilation behavior on every change. Maybe just parse syntax and then do a full semantic analysis on save.

**Comment by ray-delossantos** [comment]
Hello @kofno:

Just wanted to thanks for the great work you're putting in this tool, thanks to that i already changed my atom editor environment to vs-code. Is there any kind of installation instruction for using scry? is there any performance improvement with this change?.

Rayner

**Comment by kofno** [comment]
Thanks @raydf! I'm glad it's useful to you.

Here's the story with Scry: 

I'm using it in my local crystal-ide while I'm building Scry. Last night was a pretty stable editing session. If I can have a couple more of those, then I'll probably try to ship a release of crystal-ide w/ Scry as an optional backend. 

I'm haven't done any benchmarking. I suspect that for a single operation, scry is faster then the typescript backend, but for a series of operations, scry will appear slower. That's because I haven't added any concurrency yet. That won't impact your typing speed or anything, just may take a little longer to report errors when there is a lot of analysis going on. 

The main benefit of Scry is that I can get access to all the compiler tools in process, which I think will let me do some really cool things. Also, I'd rather write Crystal then Typescript.

Which platform do you use for development? Linux? OS X?

**Comment by ray-delossantos** [comment]
Hi @kofno:

I'm using os X. Scry we'll allow to make crazy things with macros and the AST, and an advanced autocomplete functions. 
How can i add the comments toggle function to the language?.

Thanks again for your great work.

**Comment by kofno** [comment]
Comment toggle and also bracket matching / completion are on master. I've been playing with the settings to see what I like before I release.

**Comment by kofno** [comment]
I finally have Scry building on linux using docker. It's a busy week this week, but I'm hoping to be able to release a new ide w/ optional scry support on OS X and 64bit linux.

**Comment by ray-delossantos** [comment]
Amazing news @kofno. After that release i believe you should spread the word through the google group. I believe there's a lot of crystal programmer wanting to know about this tool. 

I'll try to contribute in the upcoming weeks :).

**Comment by kofno** [comment]
Closing this for now. Work around is to use scry. I updated the crystal-ide, but you'll have to uninstall and then re-install because I decided to publish under my name instead of my LLC (but I lost all my stars and my download count 😢  🐼) . Sorry for the inconvenience.

I'll eventually need to find a more convenient way to distribute the binary files. The VSCode marketplace has a size restriction.
