### ISSUE TITLE
Join to Crystal Tools organization

### ISSUE THREAD

**Issue by faustinoaq** [kofno/crystal-ide#13]
Hi @kofno

We are adding repositories for sublime, emacs, vim, vscode, atom, etc. All in one place well documented easy to follow, collaborate and maintain. :-)

You were the first person on create a vscode extension for crystal with Language Server Protocol support. In fact [my extension](https://github.com/faustinoaq/vscode-crystal-lang) diagnostics are inspired by this extension. So, feel free to join to Crystal organization.

Thanks you for your vscode extension for Crystal. 💓

**Comment by kofno** [comment]
I can do that! Same as with scry?

**Comment by faustinoaq** [comment]
Yes, like Scry, pick the vscode team. :-)

**Comment by kofno** [comment]
DONE!
