### ISSUE TITLE
Performance issues. Multiple crystal processes keep open.

### ISSUE THREAD

**Issue by faustinoaq** [kofno/crystal-ide#7]
Hi @kofno Happy Christmas! 🎄 

My issue is about linter performance. With the last update (vscode 1.8) each time when I open a crystal file then the editor freeze after a few minutes.

The task manager looks like:
![screenshot](http://i.imgur.com/9Rx1C6f.png "task manager")

I thought that pull #5 could improve the performance but I already have these changes in my local repository.

I don't know if #3 is slowing down the performance because `--release`

Bye! 🙋‍♂️

**Comment by kofno** [comment]
This has been a problem with the javascript based engine in the past. It's part of the reason I started scry. So I could have a single server process. To fix this, we may need to debounce process requests using the javascript engine.

**Comment by faustinoaq** [comment]
textDocument watchers are a big overload, mainly because every change do a new process.

[vscode-crystal-lang](https://github.com/faustinoaq/vscode-crystal-lang) keep a good performance.  because don't use too many watchers, however it still uses `child_process` to execute `crystal` commands.

I hope to use `Scry` in the future removing `child_process` overload :sweat_smile:
